# Site
title: AI Assisted Agile Software Development
author: Mike Gehard
description: Where I can post my musings on my journey in software development accompanied by an AI pair programming partner.
language: en
timezone: America/New_York
theme: icarus

# URL
url: https://mikegehard.github.io
root: /
permalink: :year/:month/:day/:title/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
