# Site
title: My Blog
author: Mike Gehard
description: A simple blog using Hexo
language: en
timezone: America/New_York
theme: icarus

# URL
url: https://mikegehard.github.io
root: /
permalink: :year/:month/:day/:title/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''

# Deployment
deploy:
  type: git
  repo: https://github.com/mikegehard/mikegehard.github.io.git
  branch: gh-pages
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
